### ISSUE TITLE
Highlighting does not match when scrolling inside fixed height textarea

### ISSUE THREAD

**Issue by ruudk** [podio/jquery-mentions-input#1]
See this screenshot: http://cl.ly/2E1e3D0r1y3c0D2z0t2h/mentions.png

As you can see the blue tag that is placed behind the textarea isn't lined up correctly. This only happens when I enter enough newlines.

**Comment by pinkeshdny** [comment]
hi,
add post with @ is working fine .. but how can be edit this post with mentioned tags?? @auchenberg

**Comment by ethanedeveloper12** [comment]
hello, how to disable jquerymentions input and reinitialize on a textarea??

**Comment by ruudk** [comment]
@ethanedeveloper12 Please start a new issue and not just comment on some random Github issue you find.
