### ISSUE TITLE
Mention two or more people with same name

### ISSUE THREAD

**Issue by aras7** [podio/jquery-mentions-input#94]
When I have data like this:

[{ id:1, name:'Kenneth Auchenberg', 'type':'contact' },
{ id:2, name:'Kenneth Auchenberg', 'type':'contact' },
{ id:3, name:'Kenneth Auchenberg',  'type':'contact' }]

It means that there are three users with ids 1,2 and 3 although  they have the same name(it is normal to find people with same name) so it should let me mentions anyone of them but it does not.

Here an example http://jsfiddle.net/aras7/U2U8G/

**Comment by sharjeelrajput** [comment]
Hey guys I am facing same issue even after updating patch ..
I have user likes adnan onee and Adnan one
When I tag both I get this view 
@[adnan onee](contact:10002734) adnan one
@djhvscf check this
